apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-alert-sa
  namespace: osc-test
  annotations:
    iam.gke.io/gcp-service-account: "kubegrc-bucket-sa@mm-k8s-lab-01.iam.gserviceaccount.com"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata:
  name: event-alert-role
rules:
  - apiGroups: ["wgpolicyk8s.io"]
    resources: ["policyreports", "clusterpolicyreports"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps.kruise.io"]
    resources: ["broadcastjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-alert-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-alert-role
subjects:
  - kind: ServiceAccount
    name: event-alert-sa
    namespace: osc-test
