apiVersion: apps.kruise.io/v1alpha1
kind: AdvancedCronJob
metadata:
  name: kubebench-scan
  namespace: osc-test
spec:
  schedule: "0 0 * * 1" # Runs every Monday at midnight
  template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: kube-bench
                image: google/cloud-sdk:slim
                env:
                  - name: NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                command:
                  - "/bin/sh"
                  - "-c"
                  - |    
                    # kube-bench installation
                    KUBE_BENCH_VERSION=0.10.1
                    curl -L https://github.com/aquasecurity/kube-bench/releases/download/v${KUBE_BENCH_VERSION}/kube-bench_${KUBE_BENCH_VERSION}_linux_amd64.deb -o kube-bench_${KUBE_BENCH_VERSION}_linux_amd64.deb
                    apt-get install ./kube-bench_${KUBE_BENCH_VERSION}_linux_amd64.deb -f && echo "kube-bench installed"
                    # scan & upload results
                    TIMESTAMP=$(date +%Y%m%d_%H%M%S) && echo Running kube-bench on node: $(NODE_NAME) && kube-bench run --targets node,policies,managedservices --benchmark gke-1.6.0 --json > /tmp/kubebench-report.json 
                    gcloud auth activate-service-account --key-file=/etc/gcp/credentials.json && gsutil cp /tmp/kubebench-report.json gs://kubegrc/scan-results/kubebench/kubebench-report-${TIMESTAMP}-$(NODE_NAME).json
                volumeMounts:
                  - name: var-lib-kubelet
                    mountPath: /var/lib/kubelet
                    readOnly: true
                  - name: etc-systemd
                    mountPath: /etc/systemd
                    readOnly: true
                  - name: etc-kubernetes
                    mountPath: /etc/kubernetes
                    readOnly: true
                  - name: home-kubernetes
                    mountPath: /home/kubernetes
                    readOnly: true
                  - name: gcp-credentials
                    mountPath: "/etc/gcp"
                    readOnly: true
            volumes:
              - name: var-lib-kubelet
                hostPath:
                  path: "/var/lib/kubelet"
              - name: etc-systemd
                hostPath:
                  path: "/etc/systemd"
              - name: etc-kubernetes
                hostPath:
                  path: "/etc/kubernetes"
              - name: home-kubernetes
                hostPath:
                  path: "/home/kubernetes"
              - name: gcp-credentials
                secret:
                  secretName: gcp-bucket-credentials
                  items:
                  - key: credentials.json
                    path: credentials.json
            restartPolicy: Never
        completionPolicy:
          type: Always
          ttlSecondsAfterFinished: 30