apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubescape-scan
  namespace: osc-test
spec:
  schedule: "0 0 * * 1" # Runs every Monday at midnight 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubescape-sa
          containers:
          - name: kubescape
            image: google/cloud-sdk:slim
            command:
              - "/bin/sh"
              - "-c"
              - |
                # Install kubescape
                curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
                # Run scan and upload to GCS
                TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                kubescape scan framework nsa,mitre --format json --format-version v2 > /tmp/kubescape-report.json
                gcloud auth activate-service-account --key-file=/etc/gcp/credentials.json
                gsutil cp /tmp/kubescape-report.json gs://kubegrc/scan-results/kubescape/kubescape-report-${TIMESTAMP}.json
            volumeMounts:
            - name: gcp-credentials
              mountPath: "/etc/gcp"
              readOnly: true
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-bucket-credentials
              items:
              - key: credentials.json
                path: credentials.json
          restartPolicy: OnFailure